global_options:
  drift_dev:
    runs_before:
      - riverpod_generator

targets:
  $default:
    builders:
      auto_route_generator:
        generate_for:
          include:
            - lib/router/app_router.dart
            - lib/**/*_page.dart
      drift_dev:
        options:
          data_class_to_companions: false
        generate_for:
          include:
            - lib/core/infrastructure/databases/**
      envied_generator|envied:
        generate_for:
          include:
            - lib/core/infrastructure/constants/env.dart
      freezed:
        options:
          format: false
        generate_for:
          include:
            - lib/core/domain/failures/**
            - lib/**/entities/**
            - lib/**/value_objects/**
            - lib/**/dtos/**
